name: rxdart_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ">=3.0.0 <4.0.0"
  test: ">=1.9.0 <2.0.0"

flutter:
  uses-material-design: true
